/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-21 06:18:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myBoardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/workspace/ThinkoGit/Thinko/Thinko/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1610503398849L));
    _jspx_dependants.put("jar:file:/C:/workspace/ThinkoGit/Thinko/Thinko/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>내 게시물</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/member.css\">\r\n");
      out.write("<style>\r\n");
      out.write("#my-board, #my-comment {\r\n");
      out.write("\tborder-bottom: 1px solid rgb(223, 223, 223);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-wrapper {\r\n");
      out.write("\theight: 320px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my-board td:hover, #my-comment td:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my-board tr>th:nth-of-type(3), #my-comment tr>th:nth-of-type(2) {\r\n");
      out.write("\twidth: 340px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my-board tr>td:nth-of-type(4), #my-comment tr>td:nth-of-type(3),\r\n");
      out.write("\t#my-comment tr>td:nth-of-type(4) {\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\tmax-width: 340px;\r\n");
      out.write("\tpadding-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my-comment tr>td:nth-of-type(4) {\r\n");
      out.write("\twidth: 240px;\r\n");
      out.write("\tmax-width: 240px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my-board tr>td:nth-of-type(2), #my-comment tr>td:nth-of-type(2) {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my-board th, #my-comment th {\r\n");
      out.write("\tbackground-color: #81479810;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#my-board td, #my-board th, #my-comment td, #my-comment th {\r\n");
      out.write("\tpadding-right: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#delete-button {\r\n");
      out.write("\tborder: 1px solid #cccccc;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tpadding-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination {\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row my-5\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "memberSideMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"container\" class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<h5>M Y &nbsp; B O A R D</h5>\r\n");
      out.write("\t\t\t\t<div class=\"list-wrapper bg-white rounded container p-3\">\r\n");
      out.write("\t\t\t\t\t<table id=\"my-board\" class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><input type=\"checkbox\" id=\"chk_all\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>게시판</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button id=\"delete-button\" type=\"button\" onclick=\"deleteMyBoard()\">삭제</button>\r\n");
      out.write("\t\t\t\t<div class=\"my-1\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"board-pagination\" class=\"pagination\"></ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br> <br> <br>\r\n");
      out.write("\t\t\t\t<h5>M Y &nbsp; R E P L Y</h5>\r\n");
      out.write("\t\t\t\t<div class=\"list-wrapper bg-white rounded container p-3\">\r\n");
      out.write("\t\t\t\t\t<table id=\"my-comment\" class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><input type=\"checkbox\" id=\"chk_all2\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>댓글</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>원문제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button id=\"delete-button\" type=\"button\" onclick=deleteMyReply()>삭제</button>\r\n");
      out.write("\t\t\t\t<div class=\"my-1\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"reply-pagination\" class=\"pagination\"></ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/member.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t jQuery.noConflict(); \r\n");
      out.write("\r\n");
      out.write("\tvar boardCp = 1;\r\n");
      out.write("\tvar replyCp = 1;\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tselectList1();\r\n");
      out.write("\t\tselectList2();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction selectList1(currentCp) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tboardCp = currentCp;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/myBoardList.do\",\r\n");
      out.write("\t\t\tdata : {\"boardCp\" : boardCp},\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\tsuccess : function(boardMap) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#my-board > tbody\").empty();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar bList = boardMap.bList;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(bList, function(index, item){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar tr = $(\"<tr>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar check = $(\"<input type='checkbox' class='chk' name='checkedRow'>\");\r\n");
      out.write("\t\t\t\t\tcheck.attr('id', item.boardNo);\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar td1 = $(\"<td>\").append(check);\r\n");
      out.write("\t\t\t\t\tvar td2 = $(\"<td>\").text(item.boardNo);\r\n");
      out.write("\t\t\t\t\tvar td3 = $(\"<td>\").text(item.boardTypeName);\r\n");
      out.write("\t\t\t\t\tvar td4 = $(\"<td>\").text(item.boardTitle);\r\n");
      out.write("\t\t\t\t\tvar td5 = $(\"<td>\").text(item.readCount);\r\n");
      out.write("\t\t\t\t\tvar td6 = $(\"<td>\").text(item.boardCreateDate);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\ttr.append(td1, td2, td3, td4, td5, td6);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#my-board > tbody\").append(tr);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("          var pInfo = boardMap.boardPInfo;\r\n");
      out.write("           boardCp = pInfo.currentPage; // 전역 변수 값 세팅\r\n");
      out.write("           var prev =  Math.floor((boardCp - 1)/pInfo.limit) * pInfo.limit;\r\n");
      out.write("           var next = Math.floor((boardCp + 4)/pInfo.limit) * pInfo.limit+1;\r\n");
      out.write("           \r\n");
      out.write("           var $pagination = $(\"#board-pagination\").eq(0); \r\n");
      out.write("           $pagination.empty();\r\n");
      out.write("           \r\n");
      out.write("\t\t\t\t\t var $liForm = $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("           var $btnForm = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           if(boardCp > pInfo.limit){\r\n");
      out.write("              // 첫페이지\r\n");
      out.write("              $li= $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList1(1)\").text(\"<<\");\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("              \r\n");
      out.write("              // 이전 페이징바\r\n");
      out.write("              $li= $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList1(\"+prev+\")\").text(\"<\");\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("              \r\n");
      out.write("           }            \r\n");
      out.write("           \r\n");
      out.write("   \t\t    \tif(pInfo.maxPage < pInfo.endPage){\r\n");
      out.write(" \t\t  \t\t\t\t pInfo.endPage = pInfo.maxPage\r\n");
      out.write(" \t\t\t\t\t\t}\r\n");
      out.write("           \r\n");
      out.write("           // 페이지 번호\r\n");
      out.write("           for(var i=pInfo.startPage ; i<=pInfo.endPage ; i++ ){\r\n");
      out.write("              $li = $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList1(\"+i+\")\").text(i);\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("           }\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           if(next <= pInfo.maxPage){\r\n");
      out.write("              // 다음 페이징바\r\n");
      out.write("              $li= $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList1(\"+next+\")\").text(\">\");\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("              \r\n");
      out.write("              // 마지막 페이징바\r\n");
      out.write("              $li = $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList1(\"+pInfo.maxPage+\")\").text(\">>\");\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("           }\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\tconsole.log(\"게시글 서버 통신 오류\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("function selectList2(currentCp) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treplyCp = currentCp;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/myReplyList.do\",\r\n");
      out.write("\t\t\tdata : {\"replyCp\" : replyCp},\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\ttraditional : true,\r\n");
      out.write("\t\t\tsuccess : function(replyMap) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t$(\"#my-comment > tbody\").empty();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar rList = replyMap.rList;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(rList, function(index, item){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar tr = $(\"<tr>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar check = $(\"<input type='checkbox' class='chk2' name='checkedRow2'>\");\r\n");
      out.write("\t\t\t\t\tcheck.attr('id', item.replyNo);\t\t\t\r\n");
      out.write("\t\t\t\t\tvar td1 = $(\"<td>\").append(check);\r\n");
      out.write("\t\t\t\t\tvar td2 = $(\"<td>\").text(item.parentBoardNo);\r\n");
      out.write("\t\t\t\t\tvar td3 = $(\"<td>\").text(item.replyContent);\r\n");
      out.write("\t\t\t\t\tvar td4 = $(\"<td>\").text(item.boardTitle);\r\n");
      out.write("\t\t\t\t\tvar td5 = $(\"<td>\").text(item.replyCreateDate);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\ttr.append(td1, td2, td3, td4, td5);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#my-comment > tbody\").append(tr);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("          var pInfo = replyMap.replyPInfo;\r\n");
      out.write("           replyCp = pInfo.currentPage; // 전역 변수 값 세팅\r\n");
      out.write("           var prev =  Math.floor((replyCp - 1)/pInfo.limit) * pInfo.limit;\r\n");
      out.write("           var next = Math.floor((replyCp + 4)/pInfo.limit) * pInfo.limit+1;\r\n");
      out.write("           \r\n");
      out.write("           var $pagination = $(\"#reply-pagination\").eq(0); \r\n");
      out.write("           $pagination.empty();\r\n");
      out.write("           \r\n");
      out.write("\t\t\t\t\t var $liForm = $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("           var $btnForm = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           if(replyCp > pInfo.limit){\r\n");
      out.write("              // 첫페이지\r\n");
      out.write("              $li= $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList2(1)\").text(\"<<\");\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("              \r\n");
      out.write("              // 이전 페이징바\r\n");
      out.write("              $li= $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList2(\"+prev+\")\").text(\"<\");\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("              \r\n");
      out.write("           }            \r\n");
      out.write("           \r\n");
      out.write("           // 페이지 번호\r\n");
      out.write("        \tif(pInfo.maxPage < pInfo.endPage){\r\n");
      out.write("        \t\t   pInfo.endPage = pInfo.maxPage\r\n");
      out.write("        \t}\r\n");
      out.write("        \t\t   \r\n");
      out.write("\t           for(var i=pInfo.startPage ; i<=pInfo.endPage ; i++ ){\r\n");
      out.write("\t        \t   \r\n");
      out.write("\t              $li = $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("\t              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("\t              $btn.attr(\"onclick\", \"selectList2(\"+i+\")\").text(i);\r\n");
      out.write("\t              $pagination.append($li.append($btn));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t           }\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           if(next <= pInfo.maxPage){\r\n");
      out.write("              // 다음 페이징바\r\n");
      out.write("              $li= $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList2(\"+next+\")\").text(\">\");\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("              \r\n");
      out.write("              // 마지막 페이징바\r\n");
      out.write("              $li = $(\"<li>\").addClass(\"page-item\");\r\n");
      out.write("              $btn = $(\"<button>\").addClass(\"page-link\");\r\n");
      out.write("              $btn.attr(\"onclick\", \"selectList2(\"+pInfo.maxPage+\")\").text(\">>\");\r\n");
      out.write("              $pagination.append($li.append($btn));\r\n");
      out.write("           }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\tconsole.log(\"댓글 서버 통신 오류\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write("\t\t// 게시글 상세보기 기능 (jquery를 통해 작업)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\", \"#my-board td:not(:first-child)\", function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar boardNo = $(this).parent().children().eq(1).text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board1/boardView.do?no=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ boardNo + \"&mb=true\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href = url;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\", \"#my-comment td:not(:first-child)\", function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar boardNo = $(this).parent().children().eq(1).text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board1/boardView.do?no=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ boardNo + \"&mb=true\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href = url;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t// 게시글 삭제 기능\r\n");
      out.write("\t\tfunction deleteMyBoard() {\r\n");
      out.write("\t\t\tvar checkedRow = $(\"input[name='checkedRow']:checked\").length;\r\n");
      out.write("\t\t\tvar boardArr = new Array();\r\n");
      out.write("\t\t\t$(\"input[name='checkedRow']:checked\").each(function() {\r\n");
      out.write("\t\t\t\tboardArr.push($(this).attr('id'));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (checkedRow == 0) {\r\n");
      out.write("\t\t\t\talert(\"선택된 글이 없습니다.\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (confirm(\"선택한 글을 삭제하시겠습니까?\")) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/deleteMyBoard.do\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\ttraditional : true,\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"boardArr\" : boardArr\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\tif (result == 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\tswal({\"icon\" : \"success\" , \"title\" : \"게시글이 삭제되었습니다.\"});\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tswal({\"icon\" : \"error\" , \"title\" : \"게시글 삭제에 실패했습니다.\"});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tselectList1()\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"서버 통신 오류\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 댓글 삭제 기능\r\n");
      out.write("\t\tfunction deleteMyReply() {\r\n");
      out.write("\t\t\tvar checkedRow2 = $(\"input[name='checkedRow2']:checked\").length;\r\n");
      out.write("\t\t\tvar replyArr = new Array();\r\n");
      out.write("\t\t\t$(\"input[name='checkedRow2']:checked\").each(function() {\r\n");
      out.write("\t\t\t\treplyArr.push($(this).attr('id'));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (checkedRow2 == 0) {\r\n");
      out.write("\t\t\t\talert(\"선택된 댓글이 없습니다.\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (confirm(\"선택한 댓글을 삭제하시겠습니까?\")) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/deleteMyReply.do\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\ttraditional : true,\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"replyArr\" : replyArr\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\tif (result == 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\tswal({\"icon\" : \"success\" , \"title\" : \"댓글 삭제되었습니다.\"});\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tswal({\"icon\" : \"error\" , \"title\" : \"댓글 삭제에 실패했습니다.\"});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tselectList2()\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"서버 통신 오류\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\", \"#chk_all\", function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif($(\"#chk_all\").is(\":checked\")){\r\n");
      out.write("\t\t\t\t\t$(\".chk\").prop(\"checked\", true);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\".chk\").prop(\"checked\", false);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\", \".chk\", function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#chk_all\").prop(\"checked\", false);\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t$(document).on(\"click\", \"#chk_all2\", function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif($(\"#chk_all2\").is(\":checked\")){\r\n");
      out.write("\t\t\t\t\t$(\".chk2\").prop(\"checked\", true);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t$(\".chk2\").prop(\"checked\", false);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\", \".chk2\", function(){\r\n");
      out.write("\t\t\t$(\"#chk_all2\").prop(\"checked\", false);\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
